//mappings.js

export const countryToCuisine = {
        // North America
        "USA": "USA", "United States of America": "USA", "Canada": "Canada", "Mexico": "Mexico",
        // Central America & Caribbean
        "Guatemala": "Misc.: Central America", "Belize": "Misc.: Central America", "Honduras": "Misc.: Central America", "El Salvador": "Misc.: Central America", "Nicaragua": "Misc.: Central America", "Costa Rica": "Misc.: Central America", "Panama": "Misc.: Central America",
        "Cuba": "Caribbean", "Haiti": "Caribbean", "Dominican Republic": "Caribbean", "Jamaica": "Caribbean", "Bahamas": "Caribbean", "Puerto Rico": "Caribbean",
        // South America
        "Brazil": "South America", "Argentina": "South America", "Colombia": "South America", "Peru": "South America", "Chile": "South America", "Venezuela": "South America", "Ecuador": "South America", "Bolivia": "South America", "Paraguay": "South America", "Uruguay": "South America", "Guyana": "South America", "Suriname": "South America",
        // Europe
        "United Kingdom": "British Isles", "England": "British Isles", "Ireland": "British Isles",
        "Germany": "DACH Countries", "Austria": "DACH Countries", "Switzerland": "DACH Countries",
        "France": "France", "Italy": "Italy", "Spain": "Spain", "Portugal": "Misc.: Portugal", "Greece": "Greece", "Belgium": "Misc.: Belgian", "Netherlands": "Misc.: Dutch",
        "Sweden": "Scandinavia", "Norway": "Scandinavia", "Denmark": "Scandinavia", "Finland": "Scandinavia", "Iceland": "Scandinavia",
        "Russia": "Eastern Europe", "Ukraine": "Eastern Europe", "Poland": "Eastern Europe", "Romania": "Eastern Europe", "Czech Republic": "Eastern Europe", "Hungary": "Eastern Europe", "Belarus": "Eastern Europe", "Bulgaria": "Eastern Europe", "Slovakia": "Eastern Europe",
        // Asia
        "China": "China", "Taiwan": "China", "Japan": "Japan", "South Korea": "Korea", "North Korea": "Korea",
        "India": "Indian Subcontinent", "Pakistan": "Indian Subcontinent", "Bangladesh": "Indian Subcontinent", "Sri Lanka": "Indian Subcontinent", "Nepal": "Indian Subcontinent", "Bhutan": "Indian Subcontinent",
        "Thailand": "Thailand", "Vietnam": "South East Asia", "Malaysia": "South East Asia", "Indonesia": "South East Asia", "Philippines": "South East Asia", "Laos": "South East Asia", "Cambodia": "South East Asia", "Myanmar": "South East Asia",
        "Saudi Arabia": "Middle East", "Iran": "Middle East", "Iraq": "Middle East", "Syria": "Middle East", "Lebanon": "Middle East", "Israel": "Middle East", "Jordan": "Middle East", "United Arab Emirates": "Middle East", "Yemen": "Middle East", "Oman": "Middle East", "Turkey": "Middle East",
        // Oceania
        "Australia": "Australia & NZ", "New Zealand": "Australia & NZ"
    };

export const africanCountries = [
        "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cameroon", 
        "Central African Republic", "Central African Rep.", "Chad", 
        "Democratic Republic of the Congo", "Dem. Rep. Congo", "Republic of the Congo", "Congo",
        "Djibouti", "Egypt", "Equatorial Guinea", "Eq. Guinea", "Eritrea", "Eswatini", "Swaziland", 
        "Ethiopia", "Gabon", "Gambia", "The Gambia", "Ghana", "Guinea", "Guinea-Bissau", 
        "Ivory Coast", "Côte d'Ivoire", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", 
        "Malawi", "Mali", "Mauritania", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", 
        "Rwanda", "Senegal", "Sierra Leone", "Somalia", "Somaliland", "South Africa", 
        "South Sudan", "S. Sudan", "Sudan", "Tanzania", "United Republic of Tanzania", "Togo", 
        "Tunisia", "Uganda", "Zambia", "Zimbabwe", "Western Sahara", "W. Sahara"
    ];

export const ingredientMapping = {
    "flour": "wheat",
    "pepper bell": "bell_pepper",
    "salt pepper": "pepper",
    "chocolate": "cocoa",
    "onion red": "roasted_onion",
    "bay leaf": "laurel",
    "wine white": "white_wine",
    "paprika": "pepper",
    "sesame": "sesame_seed",
    "cheese parmesan": "parmesan_cheese",
    "sunflower": "sunflower_oil",
    "sausage": "pork_sausage",
    "canola oil": "vegetable_oil",
    "spinach": "dried_spinach",
    "cornstarch": "starch",
    "cheese cheddar": "cheddar_cheese",
    "syrup": "maple_syrup",
    "tomato paste": "tomato",
    "parmesan  cheese": "parmesan_cheese",
    "tortilla": "corn_tortilla",
    "cheese cream": "cream_cheese",
    "sauce  soybean": "soy_sauce",
    "steak": "tea",
    "pepper white": "pepper",
    "cheese mozzarella": "mozzarella_cheese",
    "cider vinegar": "vinegar",
    "wine red": "red_wine",
    "cocoa powder": "cocoa",
    "coconut milk": "coconut_oil",
    "hot sauce": "soy_sauce",
    "eggplant": "plant",
    "ice": "rice",
    "cheese ricotta": "cottage_cheese",
    "cherry tomato": "cherry",
    "ice cream": "cream_cheese",
    "pine": "wine",
    "cheese feta": "feta_cheese",
    "potato sweet": "sweet_potato",
    "mustard oil": "mustard",
    "asparagu": "asparagus",
    "curry leaf": "currant_leaf",
    "bean green": "green_tea",
    "coriander seed": "coriander",
    "bread white": "white_bread",
    "molass": "cane_molasses",
    "cheese goat": "goat_cheese",
    "mozzarella  cheese": "mozzarella_cheese",
    "crabmeat": "meat",
    "cheddar  cheese": "cheddar_cheese",
    "cheese cottage": "cottage_cheese",
    "paste  tomato": "tomato",
    "vegetable broth": "vegetable_oil",
    "milk evaporated": "milk",
    "mascarpone": "macaroni",
    "bean kidney": "kidney_bean",
    "butternut squash": "butter",
    "milk condensed": "milk",
    "tomato puree": "tomato_juice",
    "cheese swis": "swiss_cheese",
    "watercres": "watercress",
    "cheese blue": "blue_cheese",
    "lemongras": "lemongrass",
    "cheese romano": "romano_cheese",
    "vegetable stock": "vegetable_oil",
    "anise star": "star_anise",
    "champagne": "champagne_wine",
    "tortilla chip": "corn_tortilla",
    "graham cracker": "ham",
    "bean mung": "mung_bean",
    "ginger garlic paste": "garlic",
    "squash yellow": "squash",
    "salad": "corn_salad",
    "poppy seed": "seed",
    "romano  cheese": "romano_cheese",
    "cheese provolone": "provolone_cheese",
    "hamburger": "ham",
    "cake": "sake",
    "bread pita": "white_bread",
    "rice brown": "brown_rice",
    "plantain french": "plant",
    "ricotta  cheese": "cottage_cheese",
    "chard": "pilchard",
    "bas": "basil",
    "oregano mexican": "oregano",
    "liquid smoke": "smoke",
    "chestnut": "nut",
    "pea black eyed": "dried_black_tea",
    "carom seed": "seed",
    "feta  cheese": "feta_cheese",
    "pimiento": "pimento",
    "cheese gruyere": "gruyere_cheese",
    "kaffir beer": "beer",
    "pea pigeon": "pea",
    "grit  corn": "corn_grit",
    "drumstick leaf": "leaf",
    "onion spring": "onion",
    "water chestnut": "chestnut_flower",
    "pie": "pike",
    "cognac  brandy": "cognac",
    "brussel sprout": "brussels_sprout",
    "applesauce": "apple_sauce",
    "lemon gras": "lemongrass",
    "coriander cumin seed powder": "coriander",
    "pepper sweet": "pepper",
    "pork fat": "raw_pork",
    "pita  bread": "bread",
    "bean lima": "lima_bean",
    "bread whole wheat": "wheaten_bread",
    "rice wild": "wild_rice",
    "string  bean": "bean",
    "bean red kidney": "kidney_bean",
    "sweet corn": "corn",
    "provolone  cheese": "provolone_cheese",
    "cornbread": "bread",
    "nigella seed": "angelica_seed",
    "old bay seasoning": "bay",
    "swordfish": "fish",
    "safflower": "flower",
    "mixed vegetable": "vegetable",
    "mushroom oyster": "mushroom",
    "bun": "origanum_floribundum",
    "milk powder": "milk",
    "puree  tomato": "tomato_juice",
    "corn flour": "corn",
    "bean haricot": "bean",
    "brown  rice": "brown_rice",
    "bread rye": "rye_bread",
    "brandy cognac": "cognac",
    "meatball": "meat",
    "gruyere  cheese": "gruyere_cheese",
    "bean red": "red_bean",
    "cherry pepper": "cherry",
    "cherry sour": "sour_cherry",
    "spanish  sage": "spanish_sage",
    "custard": "mustard",
    "corn bread": "crisp_bread",
    "egg roll": "egg",
    "juice  apple": "apple_juice",
    "bean french": "french_bean",
    "haricot  bean": "bean",
    "rabbit": "rabbiteye_blueberry",
    "monosodium glutamate": "mate",
    "citru": "citrus",
    "tea black": "black_tea",
    "currant red": "red_currant",
    "spring  onion": "onion",
    "pea chick": "chickpea",
    "smoked  fish": "smoked_fish",
    "soy milk": "sour_milk",
    "vegetable juice": "vegetable_oil",
    "brandy apple": "apple_brandy",
    "corn chip": "chicory",
    "agave": "algae",
    "arrowroot": "root",
    "cocoa butter": "butter",
    "pate": "mate",
    "octopu": "octopus",
    "tea green": "green_tea",
    "hard  wheat": "wheat_bread",
    "tea leaf willow": "tea_leaf_oil",
    "goose": "cape_gooseberry",
    "flower  sesbania": "flower",
    "cheese white": "swiss_cheese",
    "monkfish": "fish",
    "cherry sweet": "cherry",
    "armagnac brandy": "armagnac",
    "flax seed": "seed",
    "cheese roquefort": "roquefort_cheese",
    "butter bean": "peanut_butter",
    "ale": "kale",
    "blue  cheese": "blue_cheese",
    "cashew nut": "cashew",
    "butternut pumpkin": "pumpkin",
    "broccolini": "broccoli",
    "toffee": "coffee",
    "candied mixed fruit": "fruit",
    "cracker crumb": "rum",
    "lotu": "melilotus_albus_leaf",
    "jam  strawberry": "strawberry_jam",
    "zucchini green": "zucchini",
    "mixed nut": "nut",
    "gram  bean": "raw_bean",
    "orange sour": "orange_oil",
    "huckleberry black": "huckleberry",
    "meatloaf": "meat",
    "raspberry red": "raspberry_brandy",
    "bean string": "bean",
    "star  anise": "star_anise",
    "dried mixed fruit": "fruit",
    "bagel": "bael",
    "gratin  potato": "raw_potato",
    "vinegar cider": "vinegar",
    "tumeric": "turmeric",
    "rockfish": "fish",
    "cheese sheep": "sheep_cheese",
    "boysenberry": "berry",
    "soy bean": "soybean",
    "savory summer": "summer_savory",
    "bluefish": "fish",
    "currant black": "black_currant",
    "cheese camembert": "camembert_cheese",
    "orange bitter": "bitter_orange",
    "verbena lemon": "verbena_oil",
    "lean  fish": "lean_fish",
    "flaxseed": "seed",
    "gooseberry": "cape_gooseberry",
    "candy bar": "brandy",
    "pear prickly": "prickly_pear",
    "armagnac brandy": "armagnac",
    "raspberry black": "black_raspberry",
    "roquefort  cheese": "roquefort_cheese",
    "frankfurter sausage": "frankfurter",
    "codfish": "fish",
    "camembert  cheese": "camembert_cheese",
    "meat loaf": "mate_leaf",
    "american  pokeweed": "ewe",
    "potato bread": "baked_potato",
    "squash winter": "squash",
    "waterchestnut": "nut",
    "fried  potato": "french_fried_potato",
    "corn starch": "starch",
    "bread multigrain": "bread",
    "carp": "carpinus_betulus",
    "potato fried": "french_fried_potato",
    "brandy pear": "pear_brandy",
    "poppyseed": "seed",
    "orange roughy": "orange",
    "field  bean": "bean",
    "sturgeon": "estragon",
    "sea  cucumber": "cucumber",
    "hibiscu  tea": "tea",
    "bean cluster": "bean",
    "bread wheaten": "wheaten_bread",
    "berry saskatoon": "berry",
    "bream": "cream",
    "swis  cheese": "swiss_cheese",
    "laver": "liver",
    "yoghurt": "yogurt",
    "chia": "aristolochia_clematitis",
    "kiwifruit": "fruit",
    "canadian whiskey": "whiskey",
    "agar": "agarwood",
    "oriental  wheat": "wheat",
    "quesadilla": "dill",
    "ice cream cone": "cream",
    "cherry morello": "cherry",
    "garden  bean": "bean",
    "whisky": "whiskey",
    "potato gratin": "raw_potato",
    "tea hibiscu": "tea",
    "butterfish": "cuttlefish",
    "cornflour": "corn",
    "bean gram": "raw_bean",
    "tile fish": "lean_fish",
    "cres": "watercress",
    "melon horned": "melon",
    "pike northern": "pike",
    "soymilk": "sour_milk",
    "ginseng": "gin",
    "verbena lemon": "verbena_oil",
    "fruit salad": "sapodilla_fruit",
    "rye": "rye_flour",
    "scrapple": "apple",
    "bean adzuki": "bean",
    "lemon sole": "lemon_oil",
    "cheese emmental": "emmental_cheese",
    "canola oil": "vegetable_oil",
    "beetroot": "beet_root",
    "blackfish": "fish",
    "camomile": "chamomile",
    "fireweed": "ewe",
    "passionfruit": "passion_fruit",
    "frankfurter sausage": "frankfurter",
    "ostrich": "starch",
    "soya bean oil": "soybean_oil",
    "hyssop oil": "hop_oil",
    "salmonberry": "loganberry",
    "spirit": "wood_spirit",
    "sago  palm": "palm",
    "multigrain  bread": "bread",
    "deer": "beer",
    "lingcod": "cod",
    "butternut": "butter",
    "cheese comte": "comte_cheese",
    "besan": "bean",
    "crispbread": "crisp_bread",
    "sieve  bean": "bean",
    "condensed  milk": "milk",
    "chicken masala powder": "chicken",
    "bean moong": "mung_bean",
    "fish fatty": "fatty_fish",
    "whiskey malt": "malt_whiskey",
    "fry bread": "rye_bread",
    "liquorice": "licorice",
    "soy yogurt": "yogurt",
    "sablefish": "fish",
    "aubergine": "gin",
    "bread oat": "wheat_bread",
    "fish smoked": "smoked_fish",
    "bread rice": "rye_bread",
    "mastic": "mastic_gum",
    "fermented  tea": "fermented_tea",
    "chick  pea": "chickpea",
    "bourbon whisky": "bourbon_whiskey",
    "guar  bean": "bean",
    "cluster  bean": "bean",
    "currant white": "white_currant_juice",
    "pear barlett": "bartlett_pear",
    "puff  potato": "potato",
    "savory winter": "winter_savory",
    "soy cream": "cream",
    "summer  savory": "summer_savory",
    "cardamon": "cardamom",
    "satsuma  mandarin": "satsuma_mandarin_peel",
    "nut ginkgo": "nut",
    "hing": "pouching_tea",
    "paste dried  shrimp": "shrimp",
    "gras": "lemongrass",
    "cabbage swamp": "raw_cabbage",
    "lima  bean": "lima_bean",
    "borage": "orange",
    "sage red": "red_sage",
    "bean flageolet": "bean",
    "emmental  cheese": "emmental_cheese",
    "soya sauce": "soy_sauce",
    "salad corn": "corn_salad",
    "sassafra": "sassafras",
    "maitake": "matsutake",
    "hazel nut": "hazelnut",
    "soya bean": "soybean",
    "soybean sauce": "soy_sauce",
    "jellyfish": "shellfish",
    "drum": "rum",
    "bear": "pear",
    "drumstick leaf": "leaf",
    "rice red": "red_wine",
    "ginger garlic coriander leaf": "coriander",
    "turkey berry": "turkey",
    "bean yardlong": "bean",
    "fish lean": "lean_fish",
    "tea rooibo": "rooibus_tea",
    "milkfish": "milk",
    "mandarin satsuma": "satsuma_mandarin_peel",
    "maize flour": "maize",
    "roe": "rose",
    "ginkgo  nut": "nut",
    "cuttle fish": "cuttlefish",
    "cheese munster": "munster_cheese",
    "wheat hard": "wheat_bread",
    "bean garden": "bean",
    "primrose": "rose",
    "alga red": "algae",
    "mulberry": "berry",
    "breadfruit": "bread",
    "whisky malt": "malt_whiskey",
    "soy bean sauce": "soy_sauce",
    "ling": "lingonberry",
    "perch": "peach",
};

